### PR TITLE
[wip] PR first draft.

### PR DESCRIPTION
**Pull request by OAyomide**
add barebones process fn for python module

### CODE REVIEW

**Comment by OAyomide** [comment]
This is it the first draft of the PR. i just finally got around to having a stable PR but (probably) doesnt do much. At the moment, `rust-python` doesnt seem to play well (with zflow) and i am not sure exactly why

**Comment by darmie** [comment]
Nice. Let's use this boilerplate until we have a preferred runtime executor for Python scripts. 

For now try to remove JS references and replace them with Python.. @OAyomide

**Comment by OAyomide** [comment]
> Nice. Let's use this boilerplate until we have a preferred runtime executor for Python scripts.
> 
> For now try to remove JS references and replace them with Python.. @OAyomide

Oh yeah for sure. didnt realize i had such untidy references 👍🏾

**Comment by darmie** [comment]
Closing because there are many breaking changes since in main the last update to the PR

**Pull request closed without merging**
